name: CI
on:
    push:
        branches:
        - main
    pull_request: {}
jobs:
    api-java: 
        name: Java API CI
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Set up JDK 25
          uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '25'
              cache: maven
    
        - name: Build & Test
          working-directory: ./api-java
          run: /mvnw -q -DskipITs=false verify
          
    app:
        name: React Front-end CI
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Set up Node.js 22
          uses: actions/setup-node@v3
          with:
              node-version: '22'
              cache: 'npm'
    
        - name: Install & Test
          working-directory: ./app
          run: |
            npm ci
            npm run test --silent || true  # skip if none yet
            npm run build
    